<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
define( 'JETPACK_DEV_DEBUG', true );
require_once(dirname(__DIR__) . '/vendor/autoload.php');
require_once(dirname(__DIR__) . '/config/application.php');
/**
 * AWS Settings
 */
// define('DBI_AWS_ACCESS_KEY_ID', env('AWS_ACCESS_KEY_ID'));
// define('DBI_AWS_SECRET_ACCESS_KEY', env('AWS_SECRET_ACCESS_KEY'));
require_once(ABSPATH . 'wp-settings.php');
